name: AC_hero
channels:
  - defaults
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - ipython
  - pytest
  - pip
  - pip:
    - git+https://github.nrel.gov/Hero/hero.git@v0.5.0#egg=hero
    - smt
    - ruff