name: AC_no_hero
channels:
  - defaults
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - ipython
  - pytest
  - pandas
  - pip
  - pip:
    - git+https://github.com/NatLabRockies/tf-melt.git
    - smt
    - ruff
    - scikit-learn==1.8.0
    - soogo==2.0.1
    - pydantic
    - langchain-core