name: AC_rental_car
channels:
  - defaults
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - ipython
  - pytest
  - pandas
  - pip
  - pip:
    - git+https://github.nrel.gov/Hero/hero.git@v0.10.0#egg=hero
    - smt
    - scikit-learn==1.8.0
    - soogo==2.0.1
    - ruff
    - pydantic
    - langchain-core