CC = g++

LDIR = /home/janelle9/.conda-envs/acEnv/lib
IDIR = /home/janelle9/.conda-envs/acEnv/include/python3.12

LIBS = -lpython3.12

main: main.cpp
	$(CC) main.cpp -o output -L $(LDIR) $(LIBS) -I $(IDIR)

